DEBUG = True
TESTING = True

SQLALCHEMY_DATABASE_URI = "postgresql://testing:testing@pg:5432/testing"
SQLALCHEMY_TRACK_MODIFICATIONS = False

COMMIT_ID = "TESTING"
SENTRY_DSN = "https://examplePublicKey@o0.ingest.sentry.io/0"
SENTRY_TRACES_SAMPLE_RATE = 0.0
SENTRY_ENVIRONMENT = "testing"

BEEVENUE_DO_WARMUP = True
BEEVENUE_STORAGE = "./test"

BEEVENUE_PUBLIC_BASE = "https://www.example.org/"
BEEVENUE_OTP_EXPIRY_SECONDS = 30

BEEVENUE_ALLOWED_CORS_ORIGINS = ["http://localhost:*"]

BEEVENUE_THUMBNAIL_SIZES = {"s": 240, "l": 600}
BEEVENUE_TINY_THUMBNAIL_SIZE = 8
BEEVENUE_MINIMUM_ASPECT_RATIO = 0.5

BEEVENUE_RULES_FILE = "test/resources/testing_rules.json"

SECRET_KEY = "TESTING_ONLY"
