version: "3"
services:
  pg:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=testing
      - POSTGRES_PASSWORD=testing
      - PGDATA=/pgtmpfs
    ports:
      - "25432:5432"
    tmpfs:
      - /pgtmpfs
  redis:
    build:
      context: .
      dockerfile: ./script/redis.Dockerfile
    ports:
      - "16379:6379"
  app:
    build:
      context: .
      dockerfile: ./script/app.Dockerfile
    image: beevenue-tests-app:beevenue-tests-app
  tests:
    build:
      context: .
      dockerfile: ./script/test.Dockerfile
    volumes:
      # Coveralls needs this to figure out the PR
      - .git:/beevenue/.git
    depends_on:
      - app
      - pg
      - redis
