version: "3"
services:
  pg:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=beevenue
      - POSTGRES_PASSWORD=beevenue
    ports:
      - "15432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data:rw
  redis:
    build:
      context: .
      dockerfile: ./script/redis.Dockerfile
    volumes:
      - ./redis-data:/var/lib/redis:rw
    ports:
      - "6379:6379"
  nginx:
    build:
      context: .
      dockerfile: ./script/nginx.Dockerfile
    volumes:
      # By mounting these files locally, we can use "sendfile" support to send the files
      # directly from this container instead of round-tripping through "app".
      - ./media:/beevenue/media:ro
      - ./thumbs:/beevenue/thumbs:ro
    ports:
      - "7000:8000"
  app:
    build:
      context: .
      dockerfile: ./script/app.Dockerfile
    volumes:
      - .:/beevenue
    depends_on:
      - pg
      - redis
      - nginx
