version: "3"
services:
  redis:
    build:
      context: .
      dockerfile: ./script/redis.Dockerfile
    ports:
      - "16379:6379"
  app:
    build:
      context: .
      dockerfile: ./script/app.Dockerfile
    image: beevenue-tests-app:beevenue-tests-app
  tests:
    build:
      context: .
      dockerfile: ./script/test.Dockerfile
    volumes:
      - .:/beevenue
    depends_on:
      - app
      - redis
