"""empty message

Revision ID: 38a2d1ad418f
Revises: 139d8410796c
Create Date: 2022-02-06 15:20:36.219053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "38a2d1ad418f"
down_revision = "139d8410796c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "medium", "width", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "medium", "height", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "medium", "filesize", existing_type=sa.BIGINT(), nullable=False
    )
    op.alter_column(
        "medium", "insert_date", existing_type=sa.DATE(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "medium", "insert_date", existing_type=sa.DATE(), nullable=True
    )
    op.alter_column(
        "medium", "filesize", existing_type=sa.BIGINT(), nullable=True
    )
    op.alter_column(
        "medium", "height", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "medium", "width", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
