"""empty message

Revision ID: 3f84ce3b7d39
Revises: f3e14d89f27f
Create Date: 2021-07-24 13:30:51.928529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3f84ce3b7d39"
down_revision = "f3e14d89f27f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        None, "mediumTagAbsence", ["medium_id", "tag_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "mediumTagAbsence", type_="unique")
    # ### end Alembic commands ###
