"""empty message

Revision ID: 9612abc1d885
Revises: 3f84ce3b7d39
Create Date: 2022-01-15 08:20:38.240146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9612abc1d885"
down_revision = "3f84ce3b7d39"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("google_id", sa.String(length=256), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "google_id")
    # ### end Alembic commands ###
