"""empty message

Revision ID: f3e14d89f27f
Revises: a19c1d2e5764
Create Date: 2021-07-23 20:19:06.666142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f3e14d89f27f"
down_revision = "a19c1d2e5764"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mediumTagAbsence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("medium_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["medium_id"],
            ["medium.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mediumTagAbsence_medium_id"),
        "mediumTagAbsence",
        ["medium_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mediumTagAbsence_tag_id"),
        "mediumTagAbsence",
        ["tag_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_mediumTagAbsence_tag_id"), table_name="mediumTagAbsence"
    )
    op.drop_index(
        op.f("ix_mediumTagAbsence_medium_id"), table_name="mediumTagAbsence"
    )
    op.drop_table("mediumTagAbsence")
    # ### end Alembic commands ###
