name: Tests
on:
  push:
    branches:
      - "feature/**"

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Build base image for tests
        run: docker-compose -p beevenue-tests -f docker-compose.tests.yml build app tests
      - name: Run tests in docker
        run: docker-compose -f docker-compose.tests.yml -p beevenue-tests run -e COVERALLS_REPO_TOKEN="${{ secrets.COVERALLS_REPO_TOKEN }}" tests
